// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNE9UiibzYa5aoh1ru0eKvif5aCTpa2c',
    appId: '1:1063481998855:web:4012733344a1ed27f834a2',
    messagingSenderId: '1063481998855',
    projectId: 'demoprima',
    authDomain: 'demoprima.firebaseapp.com',
    storageBucket: 'demoprima.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGH3Kw8OHKGQUrIHxZ7K5KZj4qslMj_xg',
    appId: '1:1063481998855:android:c0ad158a2d926408f834a2',
    messagingSenderId: '1063481998855',
    projectId: 'demoprima',
    storageBucket: 'demoprima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCEVQIOmqoQdNKoLaSQPNJCUCOT2dqdeE',
    appId: '1:1063481998855:ios:3f8194113e9cd35cf834a2',
    messagingSenderId: '1063481998855',
    projectId: 'demoprima',
    storageBucket: 'demoprima.appspot.com',
    iosBundleId: 'com.example.demoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCEVQIOmqoQdNKoLaSQPNJCUCOT2dqdeE',
    appId: '1:1063481998855:ios:7b68c3b1ea2207a3f834a2',
    messagingSenderId: '1063481998855',
    projectId: 'demoprima',
    storageBucket: 'demoprima.appspot.com',
    iosBundleId: 'com.example.demoFlutter.RunnerTests',
  );
}
